### ISSUE TITLE
Mark2 UI broken

### ISSUE THREAD

**Issue by Column01** [gsand/mark2#102]
I went to look at my server's after leaving for a bit, and came back to the Mark2 UI being broken. The border is just using other characters rather than the ones that it should be. I made no changes to Mark2 itself so this makes absolutely no sense.
This is what it looks like for me:
https://i.imgur.com/3iXG3wz.png

Installation directory: /usr/mark2/

**Comment by Column01** [comment]
[Here](https://pastebin.com/TEXhkfWE) is the mark2rc.default.properties file

**Comment by Combustible** [comment]
This looks like the terminal you are connecting with does not support the "fancy" characters mark2 uses to generate the UI. It is almost certainly a setting someplace in your SSH program (PuTTY, xterm, etc.)

**Comment by Column01** [comment]
I fixed it. My user got messeed up and changed the remote character set for my user from UTF8 to Some weird one. It was NOT mark2 whatsoever.
