### ISSUE TITLE
Getting @external error

### ISSUE THREAD

**Issue by merlinlcb** [gsand/mark2#108]
Getting @external error when trying to stop a specific server in my network of servers, the servers console is randomly getting unkown command messages and when stopping the server with mark2 stop it generates @external shutting down bungeecord(the proxy we use), the server will not kill and the server restarts itself after getting the unkown command message in console, we have tested with 4 other wrappers/panels pufferpanel, ptero, mineos, and just using a straight line. Command line, the unkown command only happens with mark2, hoping someone can assist me with these two issues, my server this is happening on goes live in a week any help would be appreciated

**Comment by Column01** [comment]
The unknown command messages are from Mark2's crash check. This means that when the command does not go through (like stopping it in bungee) it will try to restart the server on the wrapper.

**Comment by Column01** [comment]
Probably could close this.
