### ISSUE TITLE
CPU and Memory monitoring not working.

### ISSUE THREAD

**Issue by Onfimarist** [gsand/mark2#114]
On my stats I get:
cpu: __%
mem: __%

please help!

**Comment by Qrbaker** [comment]
You are likely using Python 3.X. I resolved the issue by making sure I had Python 2.7 installed, and used pip2 (rather than pip) to install the required dependencies.

I'm working on a Python3 port, but it may take time.

**Comment by gsand** [comment]
@Qrbaker Pull requests welcome 👍

**Comment by Qrbaker** [comment]
Noted. My work is on a fork here: https://github.com/Qrbaker/mark3 and I will look into submitting some upstream stuff once its stable.

**Comment by Column01** [comment]
@Onfimarist this should be fixed if you update mark2 to the latest version following the install guide. It was recently updated to python 3.
