### ISSUE TITLE
Players are not removed from player list when leaving the server

### ISSUE THREAD

**Issue by MeltedLux** [gsand/mark2#12]
When a player leaves the server they are left behind on the mark2 playerlist.

Using latest version of mark2 from git and latest Spigot 1.8 build.

![image](https://cloud.githubusercontent.com/assets/7466824/6314481/8454e1c2-b9d8-11e4-8d1b-38c178ba8a4c.png)

**Comment by vemacs** [comment]
Can reproduce. Maybe regex needs to be changed.

**Comment by gsand** [comment]
Hey, place the following line in your mark2.properties file:

`mark2.regex.quit=(?P<username>[A-Za-z0-9_]{1,16}) (?:lost connection: |)(?P<reason>.+)`
