### ISSUE TITLE
How do I get my mark2rc.properties to work?

### ISSUE THREAD

**Issue by TomLewis** [gsand/mark2#121]
Hi I have tested mark2rc.properties and .mark2rc.properties (In the wiki as named) in my root users directory, and ~reload, I have stopped and started a server and my changes have not been changed?
How do I make this activate?

**Comment by Column01** [comment]
The file should be in the home directory for whatever user you are. So if you were the user `admin` it should go be located `/home/admin/.mark2rc.properties`. By the sounds of it you have it inside the `/home/` directory

**Comment by Column01** [comment]
Closing as this should have fixed the issue, if not just reply and i'll investigate
