### ISSUE TITLE
CPU and MEMORY usage not displaying.

### ISSUE THREAD

**Issue by Onfimarist** [gsand/mark2#122]
Hello! For some reason my CPU and MEMORY usage is displaying like this:

cpu: ___%
mem: ___%

![image](https://user-images.githubusercontent.com/55112974/92652824-7c833080-f2bb-11ea-8c90-077ef41fabdd.png)

Please help me. Thanks!

**Comment by Column01** [comment]
Hey there, 
This is caused due to an error during install with the `psutil` module.

Can you do me a favor and run the command: `pip install psutil` and share what it says in the console?

**Comment by Column01** [comment]
@Onfimarist Any update on this? This usually is caused by incorrectly installed dependencies. If you no longer need help, please close the issue.

**Comment by Column01** [comment]
Please update mark2 to use the latest version and this should be fixed.
