### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by goflishMC** [gsand/mark2#128]
Is it possible to use mark2 on ubuntu 20.04?

getting this error

`2021-07-11 03:00:50 # mark2 starting...`
`2021-07-11 03:00:51 # starting bungee`
`        Traceback (most recent call last):`
`          File "/home/pixelsurge/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred  `
`            result = f(*args, **kw)`
`          File "/usr/local/share/mark2/mk2/services/process.py", line 107, in server_starting`
`            self.stat_process.start(self.parent.config['java.ps.interval'])`
`          File "/home/pixelsurge/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 194, in start`
`            self()`
`          File "/home/pixelsurge/.local/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__`
`            d = defer.maybeDeferred(self.f, *self.a, **self.kw)`
`        --- <exception caught here> ---`
`          File "/home/pixelsurge/.local/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred`
`            result = f(*args, **kw)`
`          File "/usr/local/share/mark2/mk2/services/process.py", line 166, in update_stat`
`            except psutil.error.NoSuchProcess:`
`        exceptions.AttributeError: 'module' object has no attribute 'error'`
`2021-07-11 03:00:51 # jar file: BungeeCord.jar`
`2021-07-11 03:00:51 # pid: 59011`
`2021-07-11 03:00:51 # jvm options: -Xms2G -Xmx2G -Djline.terminal=jline.UnsupportedTerminal -XX:+UseConcMarkSweepGC`
`2021-07-11 03:00:51 | [RAW] Unrecognized VM option 'UseConcMarkSweepGC'`
`2021-07-11 03:00:51 | [RAW] Error: Could not create the Java Virtual Machine.`
`2021-07-11 03:00:51 | [RAW] Error: A fatal exception has occurred. Program will exit.`
`2021-07-11 03:00:51 # fatal error: A process has ended with a probable error condition: process ended with exit code 1.`
`2021-07-11 03:00:51 # mark2 stopped.`

**Comment by goflishMC** [comment]
I removed the line in mark2 properties that had to do with UseConcMarkSweepGC and got my server to startup up, but I'm getting this error now: https://pastebin.com/8K3fLXcr

**Comment by FourDown** [comment]
Probably gonna need your Mark2 properties to resolve this

**Comment by Column01** [comment]
Try this:
https://github.com/gsand/mark2/issues/64#issuecomment-269060176

**Comment by Column01** [comment]
Seems the `python-dev` module didn't install or isn't installed correctly and it cannot get process info from the PID for the server

**Comment by goflishMC** [comment]
I'm using Java 16 open jdk
here's my mark2.properites

java.cli.X.ms=8G
java.cli.X.mx=8G
# Use whatever mark2 saved the JAR as here
mark2.jar-path=airplane*.jar
# Saving notifications aren't really useful
plugin.save.warn-message=
plugin.save.message=
# Disable monitor plugin, not sure why.
plugin.monitor.enabled=false
plugin.monitor.crash-enabled=false
plugin.monitor.ping-enabled=false
-Dnet.md_5.bungee.native.disable=true

**Comment by goflishMC** [comment]
> Seems `python-dev` didn't install or isn't installed correctly and it cannot get process info from the PID for the server. As for the first error, you likely configured the JVM arg you wanted incorrectly or are using a newer java version which doesn't support it

got this error when trying to install python-dev: https://pastebin.com/HUZ8mdwD

**Comment by goflishMC** [comment]
> Try this:
> [#64 (comment)](https://github.com/gsand/mark2/issues/64#issuecomment-269060176)
> 
> You can probably omit all but the `python-dev` package

I tried running those commands, it installed everything, but still get the same error as posted above.

**Comment by Column01** [comment]
Does `python -V` print Python 2.7?

**Comment by Column01** [comment]
Also, you don't install `python-dev`, it's a ubuntu package so it needs to be installed with `sudo apt-get install python-dev`

**Comment by goflishMC** [comment]
> python -V

https://i.imgur.com/vvCraqf.png

**Comment by goflishMC** [comment]
> Probably gonna need your Mark2 properties to resolve this

I'm using Java 16 open jdk
here's my mark2.properites: https://pastebin.com/R5KGJzbD

**Comment by Column01** [comment]
Java 16 doesn't support the JVM arg you are trying to use.
Can you also try:

```
sudo apt-get autoremove python-dev
sudo apt-get install python-dev
```

**Comment by goflishMC** [comment]
> Java 16 doesn't support the JVM arg you are trying to use.
> Can you also try:
> 
> ```
> sudo apt-get autoremove python-dev
> sudo apt-get install python-dev
> ```

still get the same issue after doing that: https://i.imgur.com/Wgfw83t.png

**Comment by Column01** [comment]
Can you try:
```
sudo apt-get autoremove python-dev
sudo apt-get install python-dev-is-python2
```

**Comment by Column01** [comment]
if the last command doesn't work, just use `sudo pip install psutil` instead

**Comment by goflishMC** [comment]
> Can you try:
> 
> ```
> sudo apt-get autoremove python-dev
> sudo apt-get install python-dev-is-python2
> sudo pip uninstall psutil
> sudo python -m pip install psutil
> ```

still get this error: https://i.imgur.com/GzRLoxp.png

**Comment by Column01** [comment]
There has to be another underlying issue causing it, that try: except should only occur if the process doesn't exist AKA it crashed loading, regardless that is not a valid error to catch (it's really `psutil.NoSuchProcess`

Do you mind editing a file locally to confirm it's not the issue?

Go to wherever you installed mark2 and edit the `/mk2/services/process.py` file and change `psutil.error.NoSuchProcess` to just  `psutil.NoSuchProcess` on line 166

**Comment by goflishMC** [comment]
> There has to be another underlying issue causing it, that try: except should only occur if the process doesn't exist AKA it crashed loading, regardless that is not a valid error to catch (it's really `psutil.NoSuchProcess`)
> 
> Do you mind editing a file locally to confirm it's not the issue?
> 
> Go to wherever you installed mark2 and edit the `/mk2/services/process.py` file and change `psutil.error.NoSuchProcess` to just `psutil.NoSuchProcess` on line 166

After making that change I get this: https://i.imgur.com/yohDYps.png

**Comment by Column01** [comment]
OK pretty sure I messed up and it installed new versions of psutil cause we didn't specify one compatible with mark2.

Try:
```
sudo pip uninstall psutil
sudo pip install psutil==0.6.1
```

**Comment by Column01** [comment]
and maybe also revert the changes I asked you to make lol

**Comment by Column01** [comment]
If for some reason it doesn't work, you should remove all mark2 dependencies and reinstall them.

See [here](https://github.com/gsand/mark2/issues/64#issuecomment-246211149) which seems to be a related issue regarding installed dependencies.

**Comment by goflishMC** [comment]
> OK pretty sure I messed up and it installed new versions of psutil cause we didn't specify one compatible with mark2.
> 
> Try:
> 
> ```
> sudo pip uninstall psutil
> sudo pip install psutil==0.6.1
> ```

I think that fixed it! I'm not getting the error anymore and it's showing my cpu and mem now in the console

**Comment by Column01** [comment]
No problem, sorry it took me so long to figure out that I forgot the version is very important haha

You can close this now if your issue is resolved

**Comment by Column01** [comment]
@goflishMC mind closing this? I don't have the perms to do it haha
