### ISSUE TITLE
Wiki install not the same as install.md

### ISSUE THREAD

**Issue by Tellik** [gsand/mark2#135]
Just to let you know,

xclip does not (always) install the correct (or any) version of the pyperclip module. 

It required an extra step of:

sudo python -m pip install pyperclip 

to ensure that pyperclip was installed to the correct version. This could be just me, but I am on a fairly stable/updated standard installation of Manjaro Linux.

**Comment by Column01** [comment]
pyperclip was added to the `requirements.txt` file as part of the install process, the commit mentioned that you need to update your dependencies which also includes installing the python modules. My apologizes for the confusion

**Comment by Tellik** [comment]
Ah, got it. I was following the install.md. I see where you're talking about now the requirements.txt in the Wiki pages.

That's where the confusion is, the main facing install instructions aren't the same as the wiki install instructions.

**Comment by Column01** [comment]
Oh! shoot. I will have to look into updating that, that's my bad.

**Comment by Column01** [comment]
OK should be updated now. Will probably move links and such to point there instead, thanks for making me aware of this, totally forgot the wiki was a thing and it should have already been up to date.
