### ISSUE TITLE
Use event contents in response

### ISSUE THREAD

**Issue by 33mhz** [gsand/mark2#15]
If there's a way to do this already, let me know.

I would love a way to use the trigger itself in the response to a trigger. For example, set a trigger for @PlayerChat that includes the chat itself in its response. AFAIK, I have to parse the log file to get the chat message.

`@PlayerChat $[do something with] ~PlayerChat`

Likewise, I'd like to be able to tell who triggered a PlayerDeath, a Join or Leave, etc.

**Comment by gsand** [comment]
Please provide an example and I'll see if I there's something that already does it or if I can write it.

**Comment by 33mhz** [comment]
@gsand In scripts.txt, I'd like to execute a shell script using @PlayerChat, and pass the name of the player who spoke and what they said to the script.
A line in scripts.txt like:

`@PlayerChat $script.sh player player_msg`

Basically if mark2 would pass me the material it's already parsing, to use in the external scripts. So I can know not just *that* a player chatted, or *that* a player died, but what they said and *who* died.

**Comment by barneygale** [comment]
Currently not possible, but you could write a python plugin that does this.

**Comment by 33mhz** [comment]
Hrm. I could simply trigger a script to parse the latest line of Minecraft's log file... That would be easy, but less friendly, IMO.

Is there any documentation/API for writing plugins?

**Comment by barneygale** [comment]
No - there's only example code.

BTW I'm the original dev but gsand is maintaining mark2. He might be able to extend the 'scripts' plugin so you can substitute in event arguments.

**Comment by 33mhz** [comment]
My Python knowledge is fairly limited. I'll try the parsing, since I can already do that, and go from there. :)

@gsand If you're interested, I'm glad to use any changes you make or suggestions you have. :+1:

**Comment by gsand** [comment]
That could get spammy quick. Also, there's the potential of bad things happening.

You should probably make a mark2 plugin. 

Examples: https://github.com/gsand/mark2/tree/master/mk2/plugins

**Comment by 33mhz** [comment]
@gsand Thanks. I was able to easily fire a script to parse the log, and locally reading the file is fast enough to pretty much always work. On first blush I can't figure out the plugin architecture, but over time hopefully I'll figure it out. :)

**Comment by gsand** [comment]
@33mhz The trigger plugin would be a good base to start off from. Let me know if you have any questions.

**Comment by 33mhz** [comment]
FYI, I did create a basic plugin variation for doing this: https://github.com/33mhz/mark2-eventfeed

Could be nice to have a place for folks to share plugins.
