### ISSUE TITLE
mark2 sessions are accessible to other users

### ISSUE THREAD

**Issue by IamGalaxias** [gsand/mark2#16]
Hello,

I recently stopped BungeeCord by typing 'end'. Everything worked just fine, but for some reason, I was suddenly attached to the screen of another user!

This is a security problem, allowing anyone to attach to somebody else's screens.

**Comment by edk0** [comment]
mark2 isn't designed to keep different users' servers separate from each other, but see [these settings](https://github.com/gsand/mark2/blob/master/mk2/resources/mark2.default.properties#L43) (umask isn't really the correct name for them…). I have a feeling the client will spew errors at you, though.

Alternatively you could pick a private directory to keep your mark2 servers in, and invoke mark2 as `mark2 -b /path/to/that/directory`.

**Comment by IamGalaxias** [comment]
I'll try that later. But the screen is actually by another user, which 
makes it quite a big problem.

Ed Kellett schreef op 19-04-15 om 18:11:

**Comment by edk0** [comment]
It's intended behaviour. mark2 deliberately shares servers by default. If you don't want that, you can have something else, but it will require extra configuration.

**Comment by IamGalaxias** [comment]
I see. But I still don't see the point in switching to another random 
screen.

**Comment by edk0** [comment]
It just switches to the next server in the list. We thought it'd be simpler and more user-friendly than exiting or something.

**Comment by barneygale** [comment]
mark2 is also not designed to do any kind of authorization. Anyone who can read/write to the socket in /tmp can do anything with your servers.

**Comment by gsand** [comment]
This isn't really a feature that's requested often. There's only this request.

It's also a relatively "gamechanging" thing that needs to be *very* well thought out.

Also, it NEEDS to be backward compatible so current users of mark2 that upgrade occasionally aren't affected negatively.

One method could be to do /tmp/mark2/groupname/ files, but that might negatively affect existing users.

Pull Requests ARE welcome btw. :smile:

Where the mark2 socket files are saved to:

"/tmp/mark2/"

https://github.com/gsand/mark2/blob/master/mk2/launcher.py#L135-L139

Where the user client looks for files to attach to:
https://github.com/gsand/mark2/blob/master/mk2/user_client.py#L439
