### ISSUE TITLE
How do we update?

### ISSUE THREAD

**Issue by FrozenBeard** [gsand/mark2#17]
Im a little anxious asking this as you may think this is an easy task, but Im worried about breaking something, how do I go about updating Mark2 without breaking anything? im using Debian 6

**Comment by Trikolon** [comment]
Just create a backup and run 'git pull'

**Comment by FrozenBeard** [comment]
Will the git pull overwrite the directories removing all my content? Also how does it know what git repository to pull? so I just cd to the mark2 directory and type in git pull!? I haven't done this before, sorry.

**Comment by Trikolon** [comment]
Depends on how you installed mark2. If you installed it by cloning this repository (git clone) in the first place you can just switch to the directory and run 'git pull'. That will not overwrite anything only warn if there are conflicts.
If you installed it without git you'll have to update the files manually. Download the latest files and copy them over your installation.

**Comment by FrozenBeard** [comment]
Yes! I used git, this will make life so much easier, Mind you I will definitely be making a backup first! Thank you Trikolon, I will attempt this when the server isn't busy :)

**Comment by gsand** [comment]
Yeah, git is the best possible way to update. it's super easy just to change to the mark2 directory and just `git pull`
