### ISSUE TITLE
How do I set the console server activity lines shown? 

### ISSUE THREAD

**Issue by FrozenBeard** [gsand/mark2#20]
When I use page up & page down to scroll through the history of events from the console, it only seems to show a few hundred lines, I need to find a way to show about 25x the amount of history to sroll back to, is there an option to set the amount of lines that can be scrolled back to?
I have tried looking through the property files here:
https://github.com/gsand/mark2/tree/master/mk2/resources
But im not really sure what to look for..

**Comment by gsand** [comment]
It shows 200 lines of scrollback as per the following line:
https://github.com/gsand/mark2/blob/master/mk2/services/user_server.py#L101

If it were to show more a higher amount of lines, it might cause issues or very long load times when switching windows or unknown issues.

**Comment by FrozenBeard** [comment]
Is there a way to just switch mark2 to being pure SSH then? I'm guessing it
uses screen or tmux? I would much prefer the performance increase in
navigating history, and have the full history, I can live without the user
list and user htop in another terminal

**Comment by gsand** [comment]
I'll test to see how many lines would cause craziness and add it.
Thinking about it, 5000 lines doesn't seem so bad.

I'll make a config option.
