### ISSUE TITLE
Console Filters

### ISSUE THREAD

**Issue by socialretard** [gsand/mark2#22]
Is this a working feature? I cannot seem to get it to work. Not exactly sure what to set "use-filter" equal to in mark2rc.properties. Thanks.

**Comment by gsand** [comment]
The filter system needs to be reworked on.

Here's a filter that blocks all pings shown in the bungeecord console. They still appear inside your logs, this just hides it from the user client (the mark2 "terminal")

    pattern.bungee-initial-handler=.*(InitialHandler has connected)
    filter.custom=chat,join,quit,hide:bungee-initial-handler
    use-filter=custom
