### ISSUE TITLE
[Feature] ~hold/~unhold the server

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#23]
Hey gsand,

nice to see that you picked up the project. :)
Do you have some time and still interested on picking up on this feature?
https://github.com/mcdevs/mark2/issues/142

~hold <time> [reason] - holds the server after the specified time with a configurable broadcast message and message on kick like "Server going into maintenance. Reason: {reason}"?
~unhold - starts the server back up

**Comment by gsand** [comment]
hold/unhold isn't a high priority feature at the moment. Most people just stop and start it back up and let bungeecord handle the rest.

I'll keep this issue open for any future discussions.

**Comment by Slind14** [comment]
expect a pull req. It is a high priority thing for us :)

**Comment by Slind14** [comment]
deployed and production testing it, pull req soon.
