### ISSUE TITLE
[Feature] Color support

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#24]
Hey,

what are the thoughts about color support? For me with a busy console output it is pretty helpful to identify the important things. E.g. you start a backup before you shutdown the server for an upgrade. The console is busy by writing one page each 1-2 seconds. The single line that says "Backup successful" is hard to spot, hence it is green, but with mark2 those colors do not show.

**Comment by gsand** [comment]
I'll add colored mark2 plugin messages tonight.

**Comment by Slind14** [comment]
:)

**Comment by Slind14** [comment]
working fine now. was probably related to a bad regex. will be included in the upcoming pull req.
