### ISSUE TITLE
Possible issue with server args?

### ISSUE THREAD

**Issue by Punkred** [gsand/mark2#26]
Hello ive been using mark2 for all my server but recently ive made a modpack server. Im using kcauldron bootstrap which needs the arguments "-r latest".

This is my config: http://pastebin.com/raw.php?i=LZhMdAqh

Maybe ive done something wrong or it just simply doesnt support all arguments you put in?

**Comment by edk0** [comment]
iirc we unconditionally insert "nogui" before the server-args. it's possible that's screwing something up?

**Comment by gsand** [comment]
You are running the *wrong* jar file.

The `KBootstrap-0.1.0-app.jar` is used to create the kcauldron.server.jar file that is used to run the kcauldron server.
