### ISSUE TITLE
Bad error handling on invalid event prefilter

### ISSUE THREAD

**Issue by Xfel** [gsand/mark2#28]
If the Event.prefilter method throws an exception due to invalid prefilter arguments, such as an invalid regex for the ServerOutput event, it will spam the console with the error log whenever the event is called. The resulting error message makes it difficult to trace down the rogue arguments though, as it does not contain any information on the source. This is rather bad as some of these regexes are defined via the config files and can therefor be edited by non-programmers. So, I'd suggest some kind of pre-validation of the prefilter arguments when the event is registered.

**Comment by gsand** [comment]
I'm gonna work on documentation in order to prevent these things, also more examples.

The only regex most people modify is the chat detection regex.

I'll add a link to regex101.com in the documentation files and add this to the list of things to add.
