### ISSUE TITLE
Send a command to all servers.

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#29]
Hey,

is there any way to send a command to all servers? When I use `mark2 send` the command gets send to the first server (alphabetical order). It would ease the management in terms of a global restart/stop.. Current use case for me is updating mark2, which requires all servers to be stopped.

**Comment by vemacs** [comment]
for f in `mark2 list`; do mark2 send -n $f $yourcommand; done

**Comment by Slind14** [comment]
:+1:

**Comment by Slind14** [comment]
@vemacs can I get the pid of each server somehow?

**Comment by Slind14** [comment]
@gsand do you know if I can get the servers pid somehow. This would be helpful to make sure that the processes ended before the script continues.

**Comment by gsand** [comment]
Why is that even necessary?

**Comment by Slind14** [comment]
I would like to automate the mark2 update. So one script that would shut down all servers, once done pull from git, start them back up.

**Comment by gsand** [comment]
good idea, I'll work on mark2 sendall <command>

**Comment by agucova** [comment]
Lol, that would be very cool.

**Comment by gsand** [comment]
https://github.com/gsand/mark2/commit/9dc5700a0e60e9e1ece81c2528da44a8bd4d12a2
