### ISSUE TITLE
Copy and Paste

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#30]
Hey,

Is there any way to make copy and paste work? paste into the input line and mark/copy from the console? If not, any chance of implementation? For us it would be highly useful and one of the biggest things we miss since using mark2.

**Comment by Slind14** [comment]
Ok, found out that it works with shift. But it comes with the issue of copying the side-parts, too. Is it possible to hide them? Kinda like https://github.com/gsand/mark2/issues/32 but hiding everything beside the console stream and input.

**Comment by gsand** [comment]
That's currently not a very high priority thing, it would require that the whole user client be rewritten.

**Comment by Slind14** [comment]
Is there a way on mac os x as shift click doesn't work there with terminal and iterm2?

**Comment by gsand** [comment]
I dont use mac os x.

Here's a link to the documentation for iterm2 that deals with selecting text.
https://iterm2.com/documentation-one-page.html#documentation-smart-selection.html

**Comment by Slind14** [comment]
The doc is about the smart select feature which allows faster selection's based on regex rules. The issue here is that you can't mark anything. On putty you can't either but by holding shift while marking or pasting it works. I tried all the combination keys that came to my mind on os x but none wanted to work.

**Comment by gsand** [comment]
I dont use mac os x.

You could try switching to a different terminal emulator or checking your terminal documentation.

**Comment by gsand** [comment]
Alt+Cmd will turn your cursor into a crosshair which lets you select text.

**Comment by Slind14** [comment]
:+1:
