### ISSUE TITLE
Hide sidebar (small monitor, mobile device)

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#32]
Is there any hot key or attach argument to hide the side bar? Using mark2 on a mobile device is nearly impossible: https://i.imgur.com/z2E1JEK.png

**Comment by skittishtrigger** [comment]
This is an issue with the device itself. or the ssh client used to log in. much about mark2 can be configured with a little looking. i use juicessh on my phone to attach to mark2 and it looks/works wonderfully.

**Comment by Slind14** [comment]
@skittishtrigger mind showing a screenshot from juicessh with attached mark2?

**Comment by skittishtrigger** [comment]
sorry it took so long, imgur was down and my wifi transfer was being a pain. lol

http://oi57.tinypic.com/346kmes.jpg

**Comment by gsand** [comment]
I use juicessh to test mark2 stuff. This doesnt really bug me. I'll eventually get to this.

A pull request would be greatly appreciated :smile:

**Comment by Slind14** [comment]
Hmm it is related to the screen resolution of the device and font size.

**Comment by gsand** [comment]
Definitely. I'll eventually get to adding a toggle command for the sidebar stuff.

**Comment by Slind14** [comment]
that would be great. alternatively a mark attach argument.

**Comment by skittishtrigger** [comment]
man, as much as you do I would do a pull if I could program :3  But is there not options in the config already to change the layout? I seem to remember messing something up and the right side was smaller and instead of lines it was all x's.
