### ISSUE TITLE
Executing mark2 via sudo and script

### ISSUE THREAD

**Issue by Silthus** [gsand/mark2#33]
Hello,

I am trying to get mark2 to be executed via a script that is called via sudo from a PHP webpage. The command executes fine but it always prints 0 servers, e.g. when executing `mark2 list`.

I also tried executing with the additional `-b /tmp/mark2` param but `mark2 list` still prints 0 servers event though when I execute it from the shell directly, it prints 7 servers.

Any thoughts?

// edit:

I am using the following PHP script to execute the mark2 restart script:

```
exec("/home/minecraft/scripts/restart-server.sh -e 'Test' -s $server", $output);
```

And this is the corresponding `restart.sh`:

```
#!/bin/bash
scriptPath=${0%/*}
. "$scriptPath/common.sh"

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.
environment="Test"
server="Azuran"

while getopts "e:s:" opt; do
    case "$opt" in
    e) environment=$OPTARG
      ;;
    s) server=$OPTARG
      ;;
    esac
done

echo "mark2 -b /tmp/mark2 list"
mark2 list -b /tmp/mark2/
echo "mark2 send -n \"$environment|$server\" \"~restart 10s\""
mark2 send -n "$environment|$server" "~restart 10s"
wait
```

**Comment by gsand** [comment]
strange, it works for me, make sure your perms are right.
