### ISSUE TITLE
Scheduler event based on server uptime

### ISSUE THREAD

**Issue by Slind14** [gsand/mark2#34]
Hey,
is there a feature build in which allows me to execute commands/events/scripts based on a servers uptime. So to say let it restart after it has been up for 6 hours instead of at 0, 6, 12, 18, 24 o'clock? The server does restart on its own every few minutes causing that the scheduler is restarting it after only a few minutes of uptime.

**Comment by gsand** [comment]
You can do something similar with your scripts.txt file, just add:

`@ServerStarted ~restart 6h`

**Comment by Slind14** [comment]
In case of restart yes. Related to commit to fix an issue with it:
https://github.com/MineYourMind/mark2/commit/a94736a87cfe1bcf54991c4b14751ed75932cf6c

**Comment by gsand** [comment]
Upon re-reading your initial comment, the server shouldn't restart on its own every few minutes.
