### ISSUE TITLE
Gray color = black in mark2

### ISSUE THREAD

**Issue by SirWilli** [gsand/mark2#35]
hey,

the gray color is shown as black in mark2 which makes it impossible to read.

**Comment by gsand** [comment]
Works for me, what color is your terminal background?

![image link](http://i.imgur.com/o5U6L6K.png)

**Comment by SirWilli** [comment]
Also black:
![](https://i.imgur.com/nHLAvaY.png)
In front of the player names where it is black is normally gray text.

**Comment by gsand** [comment]
Type the following in your terminal, it should display Hello World in Dark Gray Text.
`echo -e "\x1b[30;1m Hello World"`

**Comment by SirWilli** [comment]
Hm, that's also black. I'm using putty with default settings.

**Comment by gsand** [comment]
Also, you have it so colors actually work in console. Have you changed anything in the mark2.properties file. Also, What terminal type are you using?

I got colors working once a while back, and totally forgot how to replicated it. :smile:

**Comment by SirWilli** [comment]
Default mark2 settings and default putty settings:
![](https://i.imgur.com/Ef9R5X3.png)

Putty colours settings:
![](https://i.imgur.com/oeVea90.png)

**Comment by gsand** [comment]
Join this IRC channel, communicating via github replies will take forever.
http://irc.spi.gt/iris/?channels=mark2

**Comment by Slind14** [comment]
Not a solution but a work around is about changing Window - Colours - `The font` to `The colour`

**Comment by gsand** [comment]
Ooops, forgot to reply here in case anyone else had that issue.
Changing it to `Both` fixes it.

**Comment by Slind14** [comment]
might be something for the documentation
