### ISSUE TITLE
Bungee Server Restarting around every 3 minutes.

### ISSUE THREAD

**Issue by RafaAro** [gsand/mark2#38]
Hi, my BungeeCord server is restarting around every 3 minutes, in the console it says this: 
http://pastebin.com/rDrZefmZ
I'm using this config for BungeeCord: http://pastebin.com/WMhsLwJE
And I'm using this config for mark2 for BungeeCord: http://pastebin.com/J3uHhHe8
I'm also using the alerts and script provided in the sample folder for bungeecord of mark2.
Please can you help me solve this?
Thank you :)

**Comment by gsand** [comment]
It looks like mark2 is pinging the wrong ip address.

create a `server.properties` file in the bungeecord directory and set:
`server-ip=173.224.126.241`

**Comment by RafaAro** [comment]
Thank you! It worked :D
