### ISSUE TITLE
Spigot Server Restarting around every 3 minutes.

### ISSUE THREAD

**Issue by RafaAro** [gsand/mark2#39]
Hi, I'm having problems with my spigot server, its restarting nearly every 3 minutes, here is the pastebin: http://pastebin.com/QwY5BHjr

**Comment by agucova** [comment]
Yep

**Comment by agucova** [comment]
And in the console, Unknown command warnings appear... 2 times before it crashes

**Comment by agucova** [comment]
Always

**Comment by gsand** [comment]
2015-08-08 19:57:01 | Comando desconocido.
    2015-08-08 19:58:01 # server might have crashed: not accepting accepting console commands or crash-unknown-cmd-message is not set -- restarting.

crash-unknown-cmd-message is not set.

Add the following:

`plugin.monitor.crash-unknown-cmd-message=Comando desconocido.*`
