### ISSUE TITLE
Rebooting on server stop

### ISSUE THREAD

**Issue by MinecraftAdmin** [gsand/mark2#41]
Is there a way through scripts.txt or otherwise using Mark2 to execute ./start.sh in the server directory as soon as the server stops?

I am basically trying to have mark2 start a server back up as soon as it shuts down.

**Comment by Trikolon** [comment]
If you're using spigot, you can set a script to run if the server shuts down. 

    #!/bin/sh
# mark2 Spigot restart script
# restart-on-crash: false
# restart-script: ./start.sh

mark2 send -n ${PWD##*/} ~restart

**Comment by gsand** [comment]
You can just ~restart
or if you want to restart while ingame, you can also do use the following script:
https://github.com/gsand/mark2/blob/master/samples/start.sh
