### ISSUE TITLE
server might have crashed: not accepting accepting console commands or crash-unknown-cmd-message is not set -- restarting

### ISSUE THREAD

**Issue by FrozenBeard** [gsand/mark2#45]
For unknown reasons I have a new spigot instance running on bungeecord the same setup of plugins I use on another server, and another world that I have scanned for any issues, Out of the blue just shuts down the server the only error message that I can see is:
server might have crashed: not accepting accepting console commands or crash-unknown-cmd-message is not set -- restarting

Which is mark2 error, what is happening? and how can I stop the server just shutting down when everything should be working? This seems to have only started since I set the spigot.yml  bungeecord: true.

**Comment by FrozenBeard** [comment]
Just found https://github.com/gsand/mark2/issues/39
Going to try that, I do have a custom message set!

**Comment by FrozenBeard** [comment]
I think it fixed it, I have a very oddly formatted Unknown Command message, will this be fine?

plugin.monitor.crash-unknown-cmd-message=Shiver me timbers! Unknown Command Landlubber, try "/info" and "/help"*

**Comment by MeltedLux** [comment]
@FrozenBeard Should be fine I also had this problem before and that was the fix.

**Comment by FrozenBeard** [comment]
@MeltedLux Yup! All fixed.
