### ISSUE TITLE
mark2 doesn't start with unicode characters in mark2.properties

### ISSUE THREAD

**Issue by totemo** [gsand/mark2#46]
If you include a Minecraft colour code sequence (using the unicode section sign, U+00A7) in mark2.properties, then mark2 fails to start.

When this happens, mark2 commands like ~stop, ~restart are rendered non-functional.

Mark2's initialisation sequence is, in part:
- daemonise, redirecting all standard file handles to /dev/null
- load the configuration file
- open Twisted Python's log file

When there is a unicode character in mark2.properties, an exception is raised:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 0: ordinal not in range(128)`

at: https://github.com/gsand/mark2/blob/master/mk2/properties.py#L80

However, it is not possible to see this exception because standard output is /dev/null and the Twisted log file isn't open yet.  You have to add custom debug logging to mark2 to see this happen, and you can't use `print` because stdout is dead.

So I raise this issue partly as a warning to others and of course to see if mark2 can more gracefully handle unicode in its config.

**Comment by gsand** [comment]
@totemo hmm, for a *long time* the server ignored section symbols (§) in the terminal, looks like that isn't the case anymore.

But I'm sure it happens to other characters too.

I've been very busy lately due to by IRL business. I'll see if I can get this fixed soon.

In the meantime, use json messages.

    tellraw @a [{color:red,text:"Hey!",bold:true},{color:gray,text:" this is a WorldGuard style message!",bold:false}]
    tellraw @a [{color:light_purple,text:"[Server]"},{text:" this is a 1.7 style message!"}]
    tellraw @a {"color":"dark_purple","text":"This server is being ran using ","extra":[{"color":"green","text":"mark2.","clickEvent":{"action":"open_url","value":"https://github.com/gsand/mark2"},"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"color":"gold","text":"View on Github"}]}},"bold":"true"}]}

**Comment by Column01** [comment]
Seems to have been fixed with the python 3 port:
![image](https://user-images.githubusercontent.com/26526649/127078240-3e3b28ce-6495-4d64-8b76-6badeb0dacb8.png)
`plugin.save.message=§cMAP IS SAVING.§r`
