### ISSUE TITLE
How to use new lines in plugin.shutdown.restart-warn-message=

### ISSUE THREAD

**Issue by FrozenBeard** [gsand/mark2#51]
Ahoy!
I tried to customize the restart message to match what we have broardcast at present but it looks as if \n trys to run a command thats actually that, so a few questions, are the varaibles capable of running in-game commands? 
How could I format a new line when customizing this message, and do colors work?

**Comment by gsand** [comment]
Paste the whole line here, so I can see.

**Comment by gsand** [comment]
plugin.shutdown.alert-command=\
    say --------------------------------\n\
    say %s\n\
    say --------------------------------

**Comment by FrozenBeard** [comment]
@gsand Thanks man, what about using colours?

**Comment by gsand** [comment]
Depending on the plugin you use to broadcast, you can use & colors codes. Mark2 doesn't currently support section symbol color codes because at one point, iirc, the console stripped them.

It's on the to-do list.
