### ISSUE TITLE
Unknown Command in log

### ISSUE THREAD

**Issue by 33mhz** [gsand/mark2#53]
I get Unknown Command every minute in the server logs, starting immediately after the server starts and continuing... I'm using the serverstopped, userattach, userdetach, playerchat, playerjoin, playerquit, and playerdeath commands in `scripts.txt`. I'm using the alert plugin, backup plugin, and rss plugin. mark2 is up to date.

```
[08:01:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:02:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:03:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:04:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:05:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:06:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
[08:07:11] [Server thread/INFO]: Unknown command. Try /help for a list of commands
```

Any ideas?

**Comment by vemacs** [comment]
This is how crash-detection for console commands operates.

**Comment by ParkThePenguin** [comment]
Paste your scripts.txt

**Comment by 33mhz** [comment]
```
     # Saves the map every 15 minutes
     */15 * * * * ~save
     # Restarts server every 24 hours
     0 12 * * * ~restart 5s
     # Since the logs are already compressed in /logs
     @serverstopped $rm server.log
     15 11 * * * ~backup

     # say admin present on attach
     @UserAttach /say An admin is auditing the system.
     @UserDetach /say Admin has detached.

     @PlayerChat $python script.py 'chat' >> errors.log 2>&1
     @PlayerJoin $python script.py 'join' >> errors.log 2>&1
     @PlayerQuit $python script.py 'quit' >> errors.log 2>&1
     @PlayerDeath $python script.py 'death' >> errors.log 2>&1
```

**Comment by MeltedLux** [comment]
```
     @UserAttach /say An admin is auditing the system.
     @UserDetach /say Admin has detached.
```

Remove the /'s from these as they are console commands. As for the minutely unknown commands as @vemacs has said these are to do with the way mark2 detects a crash by-console. If you do not want mark2 to detect crashing you can change this in your mark2.properties by adding:
[`plugin.monitor.crash-enabled=false`](https://github.com/gsand/mark2/blob/master/mk2/resources/mark2.default.properties#L309)

**Comment by 33mhz** [comment]
OH. Right. I thought he was saying it was indicating it was crashing - but it's sending an automated command that isn't recognized, so it can tell if MC has crashed. Until I can create a plugin to properly handle events, I'll disable the crash monitoring, because it's not friendly with my log parsing.

Thanks. The attach/detach messages work, fwiw.
