### ISSUE TITLE
Trying to write into the terminal window isnt working 80% of the time.

### ISSUE THREAD

**Issue by FrozenBeard** [gsand/mark2#54]
So ive been using mark2 as my main servers wrapper a few days now, and its just not working very nice. That small box at the bottom where you type things, has a good 30 second lag on each letter being entered, most times I cant even select it or type in it, its infuriating.
Not only that, you cant paste into it! 
Same goes for trying to click any of the other servers that are currently running, nearly impossible to switch, theres a good massive amount of lag.

**Comment by Trikolon** [comment]
I've experienced similar issues, but only if there was a lot of console-output.
For regular operation it's quite smooth.

**Comment by gsand** [comment]
Someone had reported this kind of issue before. It turned out, their issue was caused by their connection being saturated.

What kind of bandwidth do you fellas push?

**Comment by Trikolon** [comment]
Could well be a network issue. Is there a way to make input/output smoother even though network is slow?

**Comment by gsand** [comment]
If your line is saturated or the latency is very high, there's nothing you can do that will resolve the aesthetic issues of a slow console.
