### ISSUE TITLE
User limitation / workspaces

### ISSUE THREAD

**Issue by Noobidoo** [gsand/mark2#57]
Hi,
We have different administrators for different servers, they have different user accounts preserver.
As it is now one user can access the mark2 and attach to other servers that they should not have access to.

It's not a big deal as i trust those with shell access it's more for cleanse then any thing.

**Comment by gsand** [comment]
It's possible, just pointless for most usage cases.

You just have to `mark2 start --base /tmp/sneakysneaky serverpathorname`

You could probably just create an alias somewhere
