### ISSUE TITLE
Request: Translate Variables

### ISSUE THREAD

**Issue by RafaAro** [gsand/mark2#58]
Hi, I would like to know if it's possible to translate variables like {delay}. For example I want to translate:

`plugin.save.warn-message=WARNING: saving map in {delay}.`

to Spanish, so:

`plugin.save.warn-message=AVISO: guardando mapa en {delay}.`

But when the message shows the following image where "minute" should say "minuto" for Spanish. Is it possible to translate the variables?

Thanks!!

![c270001074f8418cab13ae3083e5abad](https://cloud.githubusercontent.com/assets/1694336/18421740/3fa62346-7846-11e6-8d72-2758e488374a.png)

**Comment by gsand** [comment]
Hi Rafa,

I'll try to fix this next time I have time.

**Comment by RafaAro** [comment]
Thanks!
