### ISSUE TITLE
[Question] website wrapper

### ISSUE THREAD

**Issue by Bennyboy1695** [gsand/mark2#61]
I was wondering if theres any known wrapper thats compatible with mark2 that will allow me to control my servers from a website aswell as the mark2 wrapper still. Or is there any plans on making a website version too ?

**Comment by phit** [comment]
Would love to see at least a basic web UI to allow non technical staff members to read the console, start & stop server etc

**Comment by Bennyboy1695** [comment]
Yeah that was what I wa shopping for too, just basic console commands ran from a web ui so that as you said a non technical person would still be able to assist.

**Comment by gsand** [comment]
Why would you want to start and stop the server externally?

**Comment by Bennyboy1695** [comment]
Yeah just the basics would be nice, I know I want just to give a staff member basic access to fix the server if it needs it I.e. Restart, maybe a command or two. 
Perfect webui for me would be similar to multicraft, but that's years of work so I'm not asking for that  :stuck_out_tongue:

**Comment by phit** [comment]
Why would you want to start and stop the server externally?
> easy of use, also giving not so trusted people access to just a certain feature, instead of full ssh access

There would be risk, especially when giving children access to it.
> sure, but how is that relevant to adding this feature
evaluating who should get access is the server owners decision and liability
