### ISSUE TITLE
Menu GUI using X Q M instead of dashes

### ISSUE THREAD

**Issue by TheConsciousness** [gsand/mark2#62]
![25827ad4-5ca6-11e6-923a-e435e53d850f](https://cloud.githubusercontent.com/assets/14192161/17516701/05a2a3ba-5e0e-11e6-9e96-f316f9d2a042.PNG)

Did I configure or install it incorrectly, or are dashes no longer used?

**Comment by KasperFranz** [comment]
It is most likely a charset problem, I had the same, changed mine to UTF-8 and it looked normal again :)

**Comment by gsand** [comment]
@KasperFranz is right.
