### ISSUE TITLE
Support symlinked server jars

### ISSUE THREAD

**Issue by Trikolon** [gsand/mark2#63]
When I create a symlink in the server directory pointing to a server jar mark2 is unable to start. Could you add support for that? This way I could have one executable for all my servers.

**Comment by Trikolon** [comment]
I was able to solve it temporarily by using a hard link.

**Comment by KasperFranz** [comment]
that seems to be working for me, what issues are you getting=?

**Comment by gsand** [comment]
`mark2.jar-path=\path\to\my\jar\file.jar`
