### ISSUE TITLE
Getting mark2 installed on Arch Linux

### ISSUE THREAD

**Issue by rikai** [gsand/mark2#66]
Looks like it's due to pyOpenSSL < 0.14 not working with modern OpenSSL as per https://github.com/pyca/pyopenssl/issues/276

Currently 0.13 is defined in requirements.txt

Additionally, arch defaults to python3, so the use of python2 should probably be explicitly defined.

Everything seems to work correctly after changing
```#!/usr/bin/env python```
to
```#!/usr/bin/env python2```
in `mark2`
then installing python2-pip and running
```sudo pip2.7 install -r /usr/local/share/mark2/requirements.txt```

:+1:

**Comment by gsand** [comment]
WIll spin up vm to fix, thanks for reporting.

**Comment by gsand** [comment]
pyOpenSSL 0.15 seems to work fine with mark2. Try it now.

**Comment by rikai** [comment]
Yep, works great! 👍 

Though the python version tomfoolery still remains, since arch uses python 3 by default.
