### ISSUE TITLE
Easily visible warning when no jar is found

### ISSUE THREAD

**Issue by rikai** [gsand/mark2#68]
I was a bit confused for a while when a server wasn't running the jar i had expected it to.

Turns out it was running the vanilla jar instead and i just hadn't noticed because there was no error message.

Seems that if there is no jar defined or if the mark2.jar-path argument is typoed, it'll fall back to using a default jar, which i didn't expect. It took me a bit to figure out what the problem was since there wasn't really a warning pointing to it.

Perhaps mark2.jar-path should be required to be defined & an error given when it isn't? Falling back to a different jar just seems... odd, because it doesn't really give you an indication that your install isn't working as you expected it to until you actually log on to it.

**Comment by gsand** [comment]
I'll make it output the jar file name on start.
