### ISSUE TITLE
mark2 starting bungeecord proxys

### ISSUE THREAD

**Issue by Theepwner** [gsand/mark2#69]
Is it just me that has to reopen puTTy/terminal after starting a bungee proxy with mark2? For instance a normal spigot server will eventually stop outputting text after the initial startup, but the bungee will continue until you reopen the terminal. Sorry if you don't know what I mean.

**Comment by gsand** [comment]
mark2 list

mark2 attach

**Comment by gsand** [comment]
You probably didn't use the bungeecord mark2 files.

https://github.com/gsand/mark2/tree/master/samples/bungeecord
