### ISSUE TITLE
Hightlight Active Server-Tab

### ISSUE THREAD

**Issue by Trikolon** [gsand/mark2#7]
Sometimes managing multiple servers in mark2 can be a bit confusing as you mix up servers.
I'd like it to highlight the tab which is currently active (Maybe just invert?).

**Comment by gsand** [comment]
You can already do that with themes.

Just create a mark2rc.properties file in your user directory, specify the theme you want to use or create your own.

https://github.com/gsand/mark2/blob/master/mk2/resources/mark2rc.default.properties
