### ISSUE TITLE
Adding extra java parameters ?

### ISSUE THREAD

**Issue by Bennyboy1695** [gsand/mark2#71]
I am having trouble with one of my plugins and it requires me to add an extra java parameter to the startup file, i was wondering how and where i would need to add this - `java.security.policy=`
Preferably a global setting for this would be nice

**Comment by MeltedLux** [comment]
https://github.com/gsand/mark2/blob/master/mk2/resources/mark2.default.properties#L145

**Comment by Bennyboy1695** [comment]
Putting it there just makes it say "Error: Could not find or load main class java.security.policy=server.policy"

**Comment by Bennyboy1695** [comment]
Managed to fix it now. Thanks:)
