### ISSUE TITLE
slow input

### ISSUE THREAD

**Issue by KasperFranz** [gsand/mark2#72]
Not filed as a bug more as a "what can we do to improve this"

We have a person connecting to the mark2, she is reporting that it takes up to 10 seconds to type lag in and execute it (background info she is in the US and server is located in Europe) she didn't have any problems before when it was runned from screens where text etc. was instant

**Comment by rikai** [comment]
I also experience this sometimes, it is especially obvious on a modded server that is generating lots out output that the wrapper has (seemingly) fallen behind on outputting.

Are the text input and output not independent of each other? If not, it might be useful to look into finding ways of making them independent of each other.

**Comment by thomas15v** [comment]
I also have the same issue. When the console is writing a lot of stuff. It goes very slow

**Comment by dwaynehulsman** [comment]
+1

**Comment by KasperFranz** [comment]
It is still a issue but the issue isn't as big as it has been

**Comment by thomas15v** [comment]
The problem is that it has to update and handle mouse/input interactions on the same thread. So unless that library introduces putting those 2 on their own thread, it won't perform any better.
