### ISSUE TITLE
Getting a Strange screen

### ISSUE THREAD

**Issue by evernife** [gsand/mark2#73]
I have mark2 working on one vps pretty cool, no problems

But in my second, i am getting this:

![image](https://cloud.githubusercontent.com/assets/11357801/20026555/9e04ccc2-a2e3-11e6-9e75-cd148e45b787.png)

And the console is really slow, the input/output of strings

**Comment by MeltedLux** [comment]
Encoding issue is nothing to do with mark2. Configure your ssh client & server correctly.

**Comment by KasperFranz** [comment]
see isue #62
