### ISSUE TITLE
[Issue] Mark2 restarting server constantly after scheduled restart

### ISSUE THREAD

**Issue by dwaynehulsman** [gsand/mark2#74]
I recently pulled and installed the lastest version of mark2 and have encountered an issue where the server keeps restarting after 10 seconds of uptime. This issue occurs after the server automatically restarts as configured in my scripts.txt.

I'm running Ubuntu 16.04 here are my files:
[mark2.peroprties](https://gist.github.com/anonymous/bc8d4d279c4cda005dc05dc0e3653aff)
[scripts.txt](https://gist.github.com/anonymous/f26afabeabf5735c0b65451e3356269a)
[start.sh](https://gist.github.com/anonymous/0e20093e8c20a9383885de42dd13c4b7)

**Comment by thomas15v** [comment]
In your scripts.txt file this is defined:

- At every minute past hour 3 restart server without warning.
- At every minute past hour 13 restart server without warning.

Please use https://crontab.guru to figure out your restart times.
https://gist.github.com/thomas15v/e07c9392f2328be5fa3b18fdd553d637

This is a script to do this:
- At 3:00 restart server without warning
- At 13:00 restart server without warning

**Comment by dwaynehulsman** [comment]
*facepalm* Thanks a lot, not sure how I can be so blind.
