### ISSUE TITLE
Define servers folders in to config.

### ISSUE THREAD

**Issue by thomas15v** [gsand/mark2#76]
I wonder if it would be possible to let us define default servers that are always running.

So we could do the following:
* mark2 startall
* see a tab with "servername [stopped]" and allow to restart the server trough that tab.

This would be amazing since I allow my console moderators trough a user called "console@server.com" with the shell set to "mark2 attach". However if a server has stopped by accident, its impossible to restart it trough that.

**Comment by gsand** [comment]
Why not use shell scripts?

**Comment by thomas15v** [comment]
We already figured that `~hold` is a thing in mark2, although we still have moderators that accidentally use `stop` but its already become a rarity.

**Comment by gsand** [comment]
Idea: If shutdown plugin is enabled, prevent the use of "stop" command. [Relevant event](https://github.com/gsand/mark2/blob/master/mk2/events/server.py#L9)

**Comment by Column01** [comment]
> Idea: If shutdown plugin is enabled, prevent the use of "stop" command. [Relevant event](https://github.com/gsand/mark2/blob/master/mk2/events/server.py#L9)

This seems like something that would cause confusion for most, also what if you need to take a server off the wrapper? You'd need to do `~stop`, wait for it to stop and then finally `~kill`

**Comment by Column01** [comment]
Gonna close it cause the suggestion is old and the initial issue was fixed.
