### ISSUE TITLE
Mark2 attach - not loaded

### ISSUE THREAD

**Issue by FilipK-CZ** [gsand/mark2#79]
Hi, I have problem with mark2 attach. I start the server and then I want connect to console, but I get empty log.

![image](https://cloud.githubusercontent.com/assets/7279856/22898971/85111d70-f229-11e6-9c80-69d0fb4d8fd4.png)

**Comment by KasperFranz** [comment]
Does your log say anything when you start the server - and is it different users you started the server with and the one you are trying to connect with?

**Comment by gamecraft45** [comment]
Everytime I using for start this command "sudo -u mcservers mark2 start Scraft-v1" (in /Servers/MC, user mcservers have permissions for this folder). Server normaly started (server start info + mark2 started). I tried connect with root, my account and with server user (mcservers). Sometimes it works with all users (but last time not work for nobody)

**Comment by gamecraft45** [comment]
For example I now started another server (Tekkit) and here attach is working, but if I want to change console to Scraft-v1, console (click or arrow) still coming back to Tekkit
![image](https://cloud.githubusercontent.com/assets/7279856/22901740/efbd554a-f232-11e6-9200-135341f25739.png)

**Comment by gamecraft45** [comment]
Any solution?
