### ISSUE TITLE
BungeeCord Command-Support ~restart & ~stop

### ISSUE THREAD

**Issue by Trikolon** [gsand/mark2#8]
When '~restart <intervals>' is used on a bungee-instance the broadcasts should be sent with 'alert <msg>' instead of 'say <msg> as BungeeCoord doesn't support it.
Same for ~stop, 'end' has to be used instead of 'stop'

**Comment by raum266** [comment]
Not all servers have Alert. Instead, the broadcast command should be settable in the mark2.properties.

**Comment by Trikolon** [comment]
Yes, only bungeecoord has it, I agree.

**Comment by gsand** [comment]
https://github.com/gsand/mark2/blob/master/mk2/resources/mark2.default.properties#L478
