### ISSUE TITLE
MARK2 IS UNCONFIGURED!

### ISSUE THREAD

**Issue by BattleHeroesNet** [gsand/mark2#81]
When i try to start server it throws me this error!
error: mark2 is unconfigured! run `mark2 config` or `mkdir /etc/mark2 && touch /etc/mark2/mark2.properties` as root

i installed it many times before and this did not happen!

**Comment by BattleHeroesNet** [comment]
fixed i copied default config to etc/mark2 location works now!

**Comment by thomas15v** [comment]
Better close this issue if you fixed it :smile:.
