### ISSUE TITLE
.sh file

### ISSUE THREAD

**Issue by ucraft02** [gsand/mark2#82]
How can I change sh file?
Sorry for bad english?

**Comment by ucraft02** [comment]
I want to use this

while true
do
   java -jar Spigot.jar
done

**Comment by thomas15v** [comment]
So far ik you don't have to do that. Mark2 automatically restarts the server.

**Comment by thomas15v** [comment]
Ehm Yes? 

I suspect you are installing an auto-restart plugin, also that you don't need. Mark2 has the ability to auto restart the server as well. See the script.txt [sample](https://github.com/gsand/mark2/blob/master/samples/scripts.txt).

**Comment by ucraft02** [comment]
I want when I write /stop server auto turn on

**Comment by ucraft02** [comment]
and if I use auto restart plugin and I write in game /autore now mark2 stop server and not turn on it back

**Comment by ucraft02** [comment]
can anyone tell me where I can change start.sh?

**Comment by gsand** [comment]
https://github.com/gsand/mark2/blob/master/samples/start.sh
