### ISSUE TITLE
Would like the ability to use the tellraw command with mark2 plugins instead of say and msg.

### ISSUE THREAD

**Issue by xfractured** [gsand/mark2#9]
I am interested in using the tellraw command instead of using say or msg as it adds a much nicer look and feel to things.

I can easily use it in the triggers and alerts plugins due to the way they are made (outputs the exact line from their respective text files). 

However, I'd also like to use them with others such as the mumble, rss, save, & shutdown plugins.
I tried using escape characters to get them the others to work, but was unable to do so.

**Comment by gsand** [comment]
yeah, you can do that, just replace their respective settings with json messages.

You could even go fancier with the json messages and make a hoverable thing

The only reason I haven't replaced all messages with json messages is because a lot of people still uses mark2 for older version which don't support it.

Here's an example:

    plugin.shutdown.stop-warn-message="WARNING: server going down for planned maintenance in {delay}."
    plugin.shutdown.stop-message="Server going down for maintenance."
    plugin.shutdown.stop-cancel-message="WARNING: planned maintenance cancelled."
    plugin.shutdown.stop-cancel-reason="WARNING: planned maintenance cancelled ({reason})."
    plugin.shutdown.restart-warn-message="WARNING: planned restart in {delay}."
    plugin.shutdown.restart-message="Server restarting."
    plugin.shutdown.restart-cancel-message="WARNING: planned restart cancelled."
    plugin.shutdown.restart-cancel-reason="WARNING: planned restart cancelled ({reason})."
    plugin.shutdown.alert-command=tellraw @a %s
