### ISSUE TITLE
Docker - error not binding to port

### ISSUE THREAD

**Issue by OnlyBrakeForRainbows** [gsand/mark2#98]
I assume the exposed port 25565 in the docker container is causing this issue as it will be binded to allow the server to be joined through the host IP.

Is there any way around this?
Thanks

**Comment by OnlyBrakeForRainbows** [comment]
Also `server.properties` is set to `server-port=25565` and `server-ip=`

**Comment by Trikolon** [comment]
I don't see how this is related to the project?

**Comment by OnlyBrakeForRainbows** [comment]
Oops sorry I meant to say whilst running mark2 in a docker container this error occurs, apologies for the confusion
